# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

image: rabits/qt:5.15-desktop

build:
  stage: build
  before_script:
      #download boost
     - wget -O boost_1_77_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.77.0/boost_1_77_0.tar.gz/download
     - tar xzvf boost_1_77_0.tar.gz 
     - cd boost_1_77_0/
     #install dependencies
     - apt update && apt -y install make autoconf cmake python-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev
     #bootstrap boost
     - ./bootstrap.sh --prefix=/usr/local
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"
